cdule:
  # DATABASE, MEMORY
  type: DATABASE
  consistency: AT_MOST_ONCE

database:
  type: mysql
  url: mysql://root:root@localhost:5432/sample?charset=utf8&parseTime=True&loc=Local
  maxIdleConnections: 10
  maxOpenConnections: 100